### ISSUE TITLE
[Android] App crash with frame processor on

### ISSUE THREAD

**Issue by zzz08900** [mgcrea/vision-camera-barcode-scanner#3]
Not sure if this goes here but my app crashes within ~1 sec of mounting a camera view with this frame processor.

Android 12, vision-camera v3.3.1,  react-native-worklets-core v0.2.2, RN 0.72

Camera view works alright without frame processor

Relevant logs might be:
```
10-12 23:56:20.552  8102  8240 E AndroidRuntime: FATAL EXCEPTION: mrousavy/VisionCamera.video
10-12 23:56:20.552  8102  8240 E AndroidRuntime: Process: com.visioncamerav3test, PID: 8102
10-12 23:56:20.552  8102  8240 E AndroidRuntime: com.facebook.jni.CppException: Compiling JS failed: 1:1:invalid empty parentheses '( )' Buffer size 3 starts with: 280a29
10-12 23:56:20.552  8102  8240 E AndroidRuntime:        at com.mrousavy.camera.frameprocessor.FrameProcessor.call(Native Method)
10-12 23:56:20.552  8102  8240 E AndroidRuntime:        at com.mrousavy.camera.core.VideoPipeline._init_$lambda$0(VideoPipeline.kt:107)
10-12 23:56:20.552  8102  8240 E AndroidRuntime:        at com.mrousavy.camera.core.VideoPipeline.$r8$lambda$EMriwS_FKhtjTFtppM84Z5V8tiI(Unknown Source:0)
10-12 23:56:20.552  8102  8240 E AndroidRuntime:        at com.mrousavy.camera.core.VideoPipeline$$ExternalSyntheticLambda0.onImageAvailable(Unknown Source:2)
10-12 23:56:20.552  8102  8240 E AndroidRuntime:        at android.media.ImageReader$1.run(ImageReader.java:850)
10-12 23:56:20.552  8102  8240 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
10-12 23:56:20.552  8102  8240 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
10-12 23:56:20.552  8102  8240 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:210)
10-12 23:56:20.552  8102  8240 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:299)
10-12 23:56:20.552  8102  8240 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
10-12 23:56:20.552  8102  8240 E AndroidRuntime: JUNK_FATAL_EXCEP: FATAL EXCEPTION: mrousavy/VisionCamera.video,Process: com.visioncamerav3test, PID: 8102
```
Any idea what's going on?

**Comment by zzz08900** [comment]
I do remember someone mentioned similar issue while trying to port god old [vision-camera-code-scanner](https://github.com/rodgomesc/vision-camera-code-scanner) to vision camera v3 and its somehow related to reanimated. Will return with more info.

**Comment by zzz08900** [comment]
Seems to be a version incompatibility problem. Somehow I was using reanimated 3.4.2 and bumping it to 3.5.4 solved the problem.
